#pragma once

#define HC_SUCCESS              200            //成功

#define HC_SUCCESS_NO_RET        201          //成功，不返回给客户端
#define HC_ERROR_NO_RET        202            //已经添加错误码和信息

#define HC_ERROR                401            //错误
#define HC_ERROR_WRONG_ACCOUNT  402          //账号不存在
#define HC_ERROR_WRONG_PASSWORD 403          //密码错误
#define HC_ERROR_LOGIN_FIRST    404          //未登录
#define HC_ERROR_LOGOUT_FIRST   405          //已经登录
#define HC_ERROR_CHAR_EXIST     406          //角色名已经存在
#define HC_ERROR_CHAR_NOT_ONLINE    407     //角色不在线
#define HC_ERROR_NAME_TOO_LONG      408     //角色名太长
#define HC_ERROR_FORBIDEN_CHAT      409     //被禁言
#define HC_ERROR_NAME_ILLEGAL    410        //名字不合法
#define HC_ERROR_ACCOUNT_BE_FREEZED    411 //帐号被冻结
#define HC_ERROR_AUTH_EXPIRED    412        //验证信息已经过期
#define HC_ERROR_NOT_ENOUGH_GOLD    413     //金币不足
#define HC_ERROR_NOT_ENOUGH_SILVER    414     //筹码不足
#define HC_ERROR_NEED_MORE_VIP    415     //需要更高VIP
#define HC_ERROR_BAG_FULL    416     //背包已满
#define HC_ERROR_MAP_NOT_OPEN   417    //地图暂未开放
#define HC_ERROR_NEED_MORE_LEVEL    418     //需要更高等级
#define HC_ERROR_IN_COOLTIME_RACE   419     //竞技场挑战冷却中
#define HC_ERROR_NOT_ENOUGH_BAG_SIZE    420     //仓库格不够
#define HC_ERROR_NOT_ENOUGH_SCORE    421     //积分不够
#define HC_ERROR_IN_COOLTIME    422     //冷却中
#define HC_ERROR_NEED_MORE_CASTLE_LEVEL    423     //需要更高城堡等级
#define HC_ERROR_NEED_MORE_METALLURGY_LEVEL    424     //需要更高炼金房等级
#define HC_ERROR_COMBAT_ACT    425     //单回合只能进行3次进攻操作
#define HC_ERROR_NOT_ENOUGH_TIMES    426     //次数不足
#define HC_ERROR_CITY_IN_COMBAT    427     //该城池战斗中
#define HC_ERROR_IN_PROTECT    428     //保护中
#define HC_ERROR_DEFAULT_HERO    429     //出战英雄无法作为材料
#define HC_ERROR_NEED_MORE_PRESTIGE_LEVEL    430     //需要更高声望等级
#define HC_ERROR_NOT_ENOUGH_GEM    431     //道具不足
#define HC_ERROR_NAME    432    //该角色名不存在
#define HC_ERROR_SEND_MAIL_INVALID_DEST 433    //发送失败，收信人不存在
#define HC_ERROR_PK_WAIT_ERROR 434    //请求已过期
#define HC_ERROR_TARGET_IN_COMBAT 435    //对方正在与其他玩家战斗中
#define HC_ERROR_TREASURE_NOT_ENOUGH_TIMES    436     //该玩家宝藏已被打劫两次，大侠放过他吧
#define HC_ERROR_HERO_FULL    437     //英雄位已满
#define HC_ERROR_GUILD_MAX_ASSISTANT    438    //公会副会长已满
#define HC_ERROR_GUILD_NAME_EXIST   439     //公会名字已存在
#define HC_ERROR_NOT_JOIN_GUILD     440     //未加入公会
#define HC_ERROR_GUILD_OFFICAL_LIMIT    441 //权限不足
#define HC_ERROR_GUILD_MAX_MEMBERS    442   //会员数已达上限
#define HC_ERROR_ALREADY_IN_GUILD    443   //已经加入公会
#define HC_ERROR_GUILD_ALREADY_APPLY    444   //已经提交申请
#define HC_ERROR_UPGRADE_EQUIPT_TOO_MORE    445   //超过允许宝石数量上限
#define HC_ERROR_MAIL_ATTACH    446   //没有附件
#define HC_ERROR_USE_VIP_CARD   447     //使用此道具增加的vip经验无法超过上限的80%
#define HC_ERROR_DAILY_SCORE_MAX   448     //今日已达任务次数上限
#define HC_ERROR_NOT_ENOUGH_PK_SILVER   449     //筹码过低（基础筹码4倍）不足以进入战斗
#define HC_ERROR_FIND_BACK   450     //请先完成今日次数
#define HC_ERROR_SELF_IN_COMBAT 451    //你正在被其他玩家挑战
#define HC_ERROR_INSPIRE_MAX 452   //鼓舞等级满
#define HC_ERROR_BOSS_NOT_OPEN 453  //boss还没开启
#define HC_ERROR_BOSS_EVENT_END 454 //boss已经结束
#define HC_ERROR_BOSS_WAITING 455 //boss即将开始
#define HC_ERROR_BOSS_NOT_ENTER 456 //请先加入boss战
#define HC_ERROR_TARGET_IN_PK 457   //目标在筹码场房间中
#define HC_ERROR_NO_PK_ROOM 458     //找不到房间
#define HC_ERROR_NEED_PASSWORD 459  //需要密码
#define HC_ERROR_PK_ROOM_FULL 460     //房间已满
#define HC_ERROR_PK_ROOM_GAME 461     //房间已经开战
#define HC_ERROR_PK_START_NOT_READY 462     //等候其他玩家准备
#define HC_ERROR_NOT_JOIN_ROOM 463     //没有加入房间
#define HC_ERROR_AUCTION_BID_OWN 464    //无法竞拍自己的物品
#define HC_ERROR_AUCTION_HIGHER_BID 465    //需要出更高价格
#define HC_ERROR_INLAY_TYPE 466     //镶嵌类型不匹配
#define HC_ERROR_INLAY_FULL 467     //镶嵌位已满

