#pragma once

enum admin_cmds_enum
{
    admin_empty_cmd = 0,
    //每日更新
    admin_daily_reset = 1,
    //定时恢复军令
    admin_recover_ling,
    //保存玩家数据
    admin_save_db,
    //更新角色排名
    admin_updateRank,
    //更新英雄排名
    admin_updateHeroRank,
    //更新军团排名
    admin_updateCorpsRank,
    //开启boss战斗
    admin_openBoss,
    //关闭boss战斗
    admin_closeBoss,
    //记录在线人数
    admin_saveOnlines,
    //刷新商店
    admin_resetShop,
    //刷新屯田
    admin_resetFarm,
    //每年冬季晚上23点发竞技排名奖
    admin_raceAwards,
    //测试竞技场排名奖
    admin_debug_raceAwards,
    
    //开放阵营战
    admin_openCampRace,
    //关闭阵营战
    admin_closeCampRace,
    //每周1凌晨0點更新
    admin_WeekReset,
    //给测试人员加金币
    admin_addGold,
    //加银币
    admin_addSilver,
    //加军令
    admin_addLing,
    //开启调试
    admin_openDebug,
    //心跳处理
    admin_heartBeat,
    //开启多人副本
    admin_openGroupCopy,
    //关闭多人副本
    admin_closeGroupCopy,
    //调整关卡进度
    admin_setTempo,
    //加英雄
    admin_addGeneral,
    //加装备
    admin_addEquiptment,
    //加技能
    admin_setSkill,
    //设置阵型等级
    admin_setZhen,
    //加道具
    admin_addTreasure,
    //设置英雄等级
    admin_generalLevel,
    //设置英雄成长率
    admin_generalChengzhang,
    //冻结帐号
    admin_freeze_account,
    //禁言
    admin_gag_char,
    //设置VIP等级
    admin_set_vip,
    //设置装备强化等级
    admin_setEquiptment,
    //设置兵器等级
    admin_setWeapon,
    //设置声望
    admin_setPrestige,
    //增加声望
    admin_addPrestige,
    //增加武将宝物
    admin_addBaowu,
    //梅花易数获得物品
    admin_lottery_get,
    //重新加载屏蔽字
    admin_reload_filter,
    //军团每日更新本日貢獻
    admin_corpsDailyReset,
    //重置梅花易数积分
    admin_resetLotteryScore,
    //清除所有洗髓点
    admin_clear_wash,
    //设置武将洗髓点
    admin_set_wash,
    //设置武将成长
    admin_set_growth,
    //删除武将
    admin_del_general,
    //修改战马
    admin_set_horse,
    //修改军团等级和经验
    admin_set_corps,
    //修改角色军团贡献
    admin_set_corps_contribute,
    //修改梅花易数积分
    admin_set_lottery_score,
    //修复传承
    admin_fix_inherrit,
    //设置武将天赋
    admin_setGenius,
    //清除充值奖励
    admin_clear_recharge_event_reward,
    //重新加载充值活动
    admin_reload_recharge_event,
    //重置军令福利
    admin_reset_welfare,
    //重置军令福利2
    admin_reset_welfare2,
    //gm福利
    admin_gm_reward,
    //检查临时vip
    admin_checkTmpVip,
    //每周日24点劫镖排行
    admin_guardAwards,
    //开启洗髓打折活动
    admin_open_wash_event,
    //商店打折活动
    admin_open_shop_discount,
    //家丁双倍活动
    admin_open_servant_event,
    //战马培养活动
    admin_open_horse_event,
    //免费VIP4活动
    admin_open_free_vip4,
    //竞技场免费次数
    admin_set_race_free_times,
    //重生打折活动
    admin_open_reborn_discount,
    //修复阵型数据
    admin_fix_zhen,
    //发放礼包
    admin_add_libao,
    //升级装备打折活动
    admin_open_enhance_equipment_event,
    //护送粮饷活动开启
    admin_guard_event,
    admin_set_guard_times,
    admin_set_guard_fac,
    //增加宝石
    admin_add_baoshi,
    //刷新宝石商店
    admin_refresh_baoshishop,
    //更新军团人数上限
    admin_update_corps_limit,
    //开启消费有礼活动
    admin_open_feedback,
    //关闭消费有礼活动
    admin_close_feedback,
    //调试消费有礼活动
    admin_debug_feedback,
    //修复好友邀请分享数据(加军团)
    admin_fix_share_data,
    //军团祭祀活动
    admin_corps_jisi,
    //护送重置
    admin_guard_reset,
    //日服邀请好友奖励 参数1：角色ID   参数2：0邀请奖励，1被邀请奖励
    admin_jp_set_invite,
    //战马培养折扣
    admin_horse_discount,
    //商店刷新次数倍数
    admin_shop_refresh_more,
    //设置机器军团团长
    admin_set_robot_corps_leader,
    //开启关闭机器人军团 1开启，0关闭
    admin_open_robot_corps,
    //创建一个机器人军团
    admin_create_robot_corps,
    //开启军团战报名
    admin_open_corps_fighting_singup,
    //开始军团战
    admin_start_corps_fighting,
    //重置军团boss
    admin_reset_jt_boss,
    //领取支线任务
    admin_trunk_task,
    //演兵道具返还
    admin_training_back,
    //移除沉迷状态
    admin_remove_chenmi,
    //开启抽奖活动
    admin_open_lottery,
    //关闭抽奖活动
    admin_close_lottery,
    //清除抽奖
    admin_clear_lottery_msg,
    //设置抽奖文字信息
    admin_set_lottery_literal,
    //设置军团收益系数
    admin_set_corpsFactor,
    //设置贸易收益系数
    admin_set_tradeFactor,
    //设置八卦阵收益系数
    admin_set_mazeFactor,
    //设置阵营战收益系数
    admin_set_campRaceFactor,
    //设置竞技场收益系数
    admin_set_arenaFactor,
    //设置屯田收益系数
    admin_set_farmFactor,
    //设置神兽实际收益
    admin_set_bossFactor,
    //设置家丁收益
    admin_set_servantFactor,
    //更新cdn
    admin_update_cdn,
    //重置武将将魂等级
    admin_reset_gsoul,
    //设置护送加成时段收益系数
    admin_set_guardFactor,
    //重新模拟冲值活动
    admin_reprocess_recharge_event,
	//设置商城折扣
	admin_change_mall_discount,
};

#include <string>

void initAdminCmds();
int getAdminCmds(const std::string& cmds);

